CREATE TABLE users (
  id uuid GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email character varying not null,
  name character varying not null,
  challengeable boolean default false not null,
  bio text,
  last_sign_in_at timestamp with time zone,
  avatar character varying,
  role character varying default 'authenticated' not null
)