CREATE TYPE post_type AS ENUM ('presencial', 'online');

CREATE TABLE posts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inserted_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  name text not null,
  slug text generated always as (slugify(name)) stored,
  description text,
  tags text[] NOT NULL,
  seats int,
  section int REFERENCES sections(id),
  date date,
  time varchar,
  type post_type DEFAULT 'presencial' NOT NULL,
  place text,
  external_link text,
  main_image text,
  game int REFERENCES games(id)
  guest_players text[] NOT NULL,
  narrator uuid REFERENCES users(id),
  guest_narrator text
);

CREATE EXTENSION IF NOT EXISTS moddatetime SCHEMA extensions;

-- this trigger will set the "updated_at" column to the current timestamp for every update
CREATE TRIGGER handle_updated_at BEFORE UPDATE ON posts 
  FOR EACH ROW EXECUTE PROCEDURE moddatetime (updated_at);
