CREATE TABLE players (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inserted_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  user uuid REFERENCES public.users(id),
  post int REFERENCES public.posts(id)
)